[theme]
base = "light"
primaryColor = "#003366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F7FB"
textColor = "#111827"
font = "sans serif"

[server]
headless = true
enableStaticServing = true

